# Generated by Django 4.2.3 on 2023-07-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=52)),
                ('Continent', models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Africa', 'Africa'), ('Oceania', 'Oceania'), ('Antarctica', 'Antarctica'), ('South America', 'South America')], default='Asia', max_length=13)),
                ('Region', models.CharField(max_length=26)),
                ('SurfaceArea', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('IndepYear', models.SmallIntegerField(blank=True, null=True)),
                ('Population', models.IntegerField(default=0)),
                ('LifeExpectancy', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('GNP', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('GNPOld', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('LocalName', models.CharField(max_length=45)),
                ('GovernmentForm', models.CharField(max_length=45)),
                ('HeadOfState', models.CharField(blank=True, max_length=60, null=True)),
                ('Capital', models.IntegerField(blank=True, null=True)),
                ('Code2', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=35)),
                ('District', models.CharField(max_length=20)),
                ('Population', models.IntegerField(default=0)),
                ('CountryCode', models.ForeignKey(db_column='CountryCode', on_delete=django.db.models.deletion.CASCADE, to='users.country')),
            ],
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=30)),
                ('IsOfficial', models.CharField(choices=[('T', 'True'), ('F', 'False')], default='F', max_length=1)),
                ('Percentage', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('CountryCode', models.ForeignKey(db_column='CountryCode', on_delete=django.db.models.deletion.CASCADE, to='users.country')),
            ],
            options={
                'unique_together': {('CountryCode', 'Language')},
            },
        ),
    ]
